//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Input System/Player Input System/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""f0f61275-714a-44ed-b02e-a4b930a5ac48"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""853b0c28-8536-45de-a0ce-1efa741bf8b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""04109e66-83da-4e54-9a90-53ce70101556"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a0dca823-e13b-4f6b-94cb-4411541cbecf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LookAt"",
                    ""type"": ""Button"",
                    ""id"": ""aa475fb1-9a46-48a3-aac8-6757c650cae1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Projectile"",
                    ""type"": ""Button"",
                    ""id"": ""5adbcbfd-4b5a-43b6-b86f-c57c15df45c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""a5f211bb-7d36-4f7a-bf64-75dfd3c3a1a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayerSkill"",
                    ""type"": ""Button"",
                    ""id"": ""3f5cbf65-2819-4465-9ed1-1a2e1937cb1d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSkill"",
                    ""type"": ""Button"",
                    ""id"": ""0dfc74db-50eb-4eea-b867-7550367c2831"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponSkillHold"",
                    ""type"": ""Button"",
                    ""id"": ""650771d2-7f92-4c06-abcf-44d198e1b38b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseScrool"",
                    ""type"": ""Value"",
                    ""id"": ""ea368004-c85f-4d17-a1fc-899acbd2f16c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RegularAttack"",
                    ""type"": ""Button"",
                    ""id"": ""10cccaa1-cba9-455b-9138-5058b8dc5b65"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeavyAttack"",
                    ""type"": ""Button"",
                    ""id"": ""7219c35f-0578-4657-8a52-29746c5263b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WalkToggle"",
                    ""type"": ""Button"",
                    ""id"": ""f083967b-24b4-4cae-bf78-57ceb686e60c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""e2de3280-aefa-4ae3-9cff-2cebe9548a8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseHoldAction"",
                    ""type"": ""Button"",
                    ""id"": ""887fbc4a-64fe-4276-b990-c87e82ecc6e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseHoldAction"",
                    ""type"": ""Button"",
                    ""id"": ""9cb9f243-98f2-47b0-86b6-00e95d30ee4b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StatisticsTab"",
                    ""type"": ""Button"",
                    ""id"": ""2c66cd06-3a0e-4ff1-a557-5bb6550d0dfd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OptionsTab"",
                    ""type"": ""Button"",
                    ""id"": ""56ee3419-d110-477f-a4e8-259f49c935aa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""fe062c1e-7f3e-43c5-836d-348dd35298bd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""81b8666f-76dc-4f0a-beaf-754e8f4cbc28"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2214aada-be6c-409c-b23c-c981f2b4c914"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3c246085-6abf-47a6-bcca-1683e2dd2b76"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f78c4ec9-e60f-4049-8565-7f433e7366ae"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""95c5b094-66c2-41b9-aa96-0896233387b5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04cddb9d-7de2-4b81-988d-27292a3eea91"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6134cd08-f73c-48ad-95c1-9ad693fef027"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f651559e-7654-4774-be59-f234939ac938"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81f73512-d464-4069-a556-45d429af23f7"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Projectile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d12ee58d-865c-4c0b-90b8-d5e57fa9a40a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b58d607-c9eb-4a91-b61b-d76bcc546514"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22d377e6-eb2d-47d9-8262-149d5a0973bc"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RegularAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89b28623-c898-4c5e-82f6-ecc3655ab383"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ac2b243-ec77-4f16-81d1-db92b061a589"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WalkToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c32abab3-0c21-4959-b720-9c11fbabb652"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84ea7c20-31d4-4c1e-9ac7-309d5a623951"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": ""Hold(duration=1.401298E-45),Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponSkillHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3c844ed-6b61-4782-8242-0c7b927e1d11"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScrool"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6eff5ba7-6a92-4489-ae06-e9db0e6393f9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseHoldAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6afd2eeb-61d6-42f7-a9f6-7b3d9c91ae10"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseHoldAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98183f50-c0d2-43ee-bfbe-9d683e08fa54"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StatisticsTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45daee1c-f9a3-4545-a5cb-1c2faa7ec4b3"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OptionsTab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_LookAt = m_Player.FindAction("LookAt", throwIfNotFound: true);
        m_Player_Projectile = m_Player.FindAction("Projectile", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_PlayerSkill = m_Player.FindAction("PlayerSkill", throwIfNotFound: true);
        m_Player_WeaponSkill = m_Player.FindAction("WeaponSkill", throwIfNotFound: true);
        m_Player_WeaponSkillHold = m_Player.FindAction("WeaponSkillHold", throwIfNotFound: true);
        m_Player_MouseScrool = m_Player.FindAction("MouseScrool", throwIfNotFound: true);
        m_Player_RegularAttack = m_Player.FindAction("RegularAttack", throwIfNotFound: true);
        m_Player_HeavyAttack = m_Player.FindAction("HeavyAttack", throwIfNotFound: true);
        m_Player_WalkToggle = m_Player.FindAction("WalkToggle", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_LeftMouseHoldAction = m_Player.FindAction("LeftMouseHoldAction", throwIfNotFound: true);
        m_Player_RightMouseHoldAction = m_Player.FindAction("RightMouseHoldAction", throwIfNotFound: true);
        m_Player_StatisticsTab = m_Player.FindAction("StatisticsTab", throwIfNotFound: true);
        m_Player_OptionsTab = m_Player.FindAction("OptionsTab", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputActions.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_LookAt;
    private readonly InputAction m_Player_Projectile;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_PlayerSkill;
    private readonly InputAction m_Player_WeaponSkill;
    private readonly InputAction m_Player_WeaponSkillHold;
    private readonly InputAction m_Player_MouseScrool;
    private readonly InputAction m_Player_RegularAttack;
    private readonly InputAction m_Player_HeavyAttack;
    private readonly InputAction m_Player_WalkToggle;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_LeftMouseHoldAction;
    private readonly InputAction m_Player_RightMouseHoldAction;
    private readonly InputAction m_Player_StatisticsTab;
    private readonly InputAction m_Player_OptionsTab;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @LookAt => m_Wrapper.m_Player_LookAt;
        public InputAction @Projectile => m_Wrapper.m_Player_Projectile;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @PlayerSkill => m_Wrapper.m_Player_PlayerSkill;
        public InputAction @WeaponSkill => m_Wrapper.m_Player_WeaponSkill;
        public InputAction @WeaponSkillHold => m_Wrapper.m_Player_WeaponSkillHold;
        public InputAction @MouseScrool => m_Wrapper.m_Player_MouseScrool;
        public InputAction @RegularAttack => m_Wrapper.m_Player_RegularAttack;
        public InputAction @HeavyAttack => m_Wrapper.m_Player_HeavyAttack;
        public InputAction @WalkToggle => m_Wrapper.m_Player_WalkToggle;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @LeftMouseHoldAction => m_Wrapper.m_Player_LeftMouseHoldAction;
        public InputAction @RightMouseHoldAction => m_Wrapper.m_Player_RightMouseHoldAction;
        public InputAction @StatisticsTab => m_Wrapper.m_Player_StatisticsTab;
        public InputAction @OptionsTab => m_Wrapper.m_Player_OptionsTab;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @LookAt.started += instance.OnLookAt;
            @LookAt.performed += instance.OnLookAt;
            @LookAt.canceled += instance.OnLookAt;
            @Projectile.started += instance.OnProjectile;
            @Projectile.performed += instance.OnProjectile;
            @Projectile.canceled += instance.OnProjectile;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @PlayerSkill.started += instance.OnPlayerSkill;
            @PlayerSkill.performed += instance.OnPlayerSkill;
            @PlayerSkill.canceled += instance.OnPlayerSkill;
            @WeaponSkill.started += instance.OnWeaponSkill;
            @WeaponSkill.performed += instance.OnWeaponSkill;
            @WeaponSkill.canceled += instance.OnWeaponSkill;
            @WeaponSkillHold.started += instance.OnWeaponSkillHold;
            @WeaponSkillHold.performed += instance.OnWeaponSkillHold;
            @WeaponSkillHold.canceled += instance.OnWeaponSkillHold;
            @MouseScrool.started += instance.OnMouseScrool;
            @MouseScrool.performed += instance.OnMouseScrool;
            @MouseScrool.canceled += instance.OnMouseScrool;
            @RegularAttack.started += instance.OnRegularAttack;
            @RegularAttack.performed += instance.OnRegularAttack;
            @RegularAttack.canceled += instance.OnRegularAttack;
            @HeavyAttack.started += instance.OnHeavyAttack;
            @HeavyAttack.performed += instance.OnHeavyAttack;
            @HeavyAttack.canceled += instance.OnHeavyAttack;
            @WalkToggle.started += instance.OnWalkToggle;
            @WalkToggle.performed += instance.OnWalkToggle;
            @WalkToggle.canceled += instance.OnWalkToggle;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @LeftMouseHoldAction.started += instance.OnLeftMouseHoldAction;
            @LeftMouseHoldAction.performed += instance.OnLeftMouseHoldAction;
            @LeftMouseHoldAction.canceled += instance.OnLeftMouseHoldAction;
            @RightMouseHoldAction.started += instance.OnRightMouseHoldAction;
            @RightMouseHoldAction.performed += instance.OnRightMouseHoldAction;
            @RightMouseHoldAction.canceled += instance.OnRightMouseHoldAction;
            @StatisticsTab.started += instance.OnStatisticsTab;
            @StatisticsTab.performed += instance.OnStatisticsTab;
            @StatisticsTab.canceled += instance.OnStatisticsTab;
            @OptionsTab.started += instance.OnOptionsTab;
            @OptionsTab.performed += instance.OnOptionsTab;
            @OptionsTab.canceled += instance.OnOptionsTab;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @LookAt.started -= instance.OnLookAt;
            @LookAt.performed -= instance.OnLookAt;
            @LookAt.canceled -= instance.OnLookAt;
            @Projectile.started -= instance.OnProjectile;
            @Projectile.performed -= instance.OnProjectile;
            @Projectile.canceled -= instance.OnProjectile;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @PlayerSkill.started -= instance.OnPlayerSkill;
            @PlayerSkill.performed -= instance.OnPlayerSkill;
            @PlayerSkill.canceled -= instance.OnPlayerSkill;
            @WeaponSkill.started -= instance.OnWeaponSkill;
            @WeaponSkill.performed -= instance.OnWeaponSkill;
            @WeaponSkill.canceled -= instance.OnWeaponSkill;
            @WeaponSkillHold.started -= instance.OnWeaponSkillHold;
            @WeaponSkillHold.performed -= instance.OnWeaponSkillHold;
            @WeaponSkillHold.canceled -= instance.OnWeaponSkillHold;
            @MouseScrool.started -= instance.OnMouseScrool;
            @MouseScrool.performed -= instance.OnMouseScrool;
            @MouseScrool.canceled -= instance.OnMouseScrool;
            @RegularAttack.started -= instance.OnRegularAttack;
            @RegularAttack.performed -= instance.OnRegularAttack;
            @RegularAttack.canceled -= instance.OnRegularAttack;
            @HeavyAttack.started -= instance.OnHeavyAttack;
            @HeavyAttack.performed -= instance.OnHeavyAttack;
            @HeavyAttack.canceled -= instance.OnHeavyAttack;
            @WalkToggle.started -= instance.OnWalkToggle;
            @WalkToggle.performed -= instance.OnWalkToggle;
            @WalkToggle.canceled -= instance.OnWalkToggle;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @LeftMouseHoldAction.started -= instance.OnLeftMouseHoldAction;
            @LeftMouseHoldAction.performed -= instance.OnLeftMouseHoldAction;
            @LeftMouseHoldAction.canceled -= instance.OnLeftMouseHoldAction;
            @RightMouseHoldAction.started -= instance.OnRightMouseHoldAction;
            @RightMouseHoldAction.performed -= instance.OnRightMouseHoldAction;
            @RightMouseHoldAction.canceled -= instance.OnRightMouseHoldAction;
            @StatisticsTab.started -= instance.OnStatisticsTab;
            @StatisticsTab.performed -= instance.OnStatisticsTab;
            @StatisticsTab.canceled -= instance.OnStatisticsTab;
            @OptionsTab.started -= instance.OnOptionsTab;
            @OptionsTab.performed -= instance.OnOptionsTab;
            @OptionsTab.canceled -= instance.OnOptionsTab;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnLookAt(InputAction.CallbackContext context);
        void OnProjectile(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnPlayerSkill(InputAction.CallbackContext context);
        void OnWeaponSkill(InputAction.CallbackContext context);
        void OnWeaponSkillHold(InputAction.CallbackContext context);
        void OnMouseScrool(InputAction.CallbackContext context);
        void OnRegularAttack(InputAction.CallbackContext context);
        void OnHeavyAttack(InputAction.CallbackContext context);
        void OnWalkToggle(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnLeftMouseHoldAction(InputAction.CallbackContext context);
        void OnRightMouseHoldAction(InputAction.CallbackContext context);
        void OnStatisticsTab(InputAction.CallbackContext context);
        void OnOptionsTab(InputAction.CallbackContext context);
    }
}
